before:
    hooks:
        - go mod download
builds:
  - env:
        - CGO_ENABLED=0
    goos:
        - linux
        - windows
        - darwin
    goarch:
        - 386
        - amd64
        - arm
        - arm64
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
archives:
  - format: binary
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
checksum:
    name_template: 'checksums.txt'
snapshot:
    name_template: "{{ .Tag }}-next"
changelog:
    skip: true
