name: Release

on:
    pull_request:
    push:

jobs:
    releaser:
        name: Release
        runs-on: ubuntu-latest
        env:
            flags: ""
        steps:
            -   if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
                run: echo "flags=--snapshot" >> "$GITHUB_ENV"
            -
                name: Checkout
                uses: actions/checkout@v4
            -
                name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version-file: 'go.mod'
            -
                name: Run GoReleaser
                uses: goreleaser/goreleaser-action@v5
                with:
                    version: latest
                    args: release --clean ${{ env.flags }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
